- src/app/auth/page.tsx
- src/app/page.tsx
- src/components/button/GoogleLoginButton.tsx
- src/components/community/Community.tsx
- src/components/community/Dropdown.tsx
- src/components/community/DropdownList.tsx
- src/components/conversation/ConversationItem.tsx
- src/components/conversation/ConversationList.tsx
- src/utils/google.ts
🚩 관련 이슈
ex) [FEAT] #25 - 구글 OAuth 구현
📋 PR Checklist
[ ] /info 에서 회화부분 스피커 눌렀을 때 발음 들리는 기능 구현
[ ] 구글 로그인창 이동
[ ] 구글 인가코드 받기
📌 유의사항
커밋이 섞여서 회화부분이 들어갔는데 스피커 버튼 누르면 발음 소리 들리는 기능 구현
google cloud platform 에서 클라이언트 ID 발급받아 구글 로그인 구현
승인코드 받기
API 나오면 서버에 토큰 넘기는 로직 추가 필요
✅ 테스트 결과
> [FEAT] 구글 OAuth 구현

- postcss.config.js
- src/components/layout/header.tsx
- src/components/main/CardCarousel.tsx
- src/components/modal/LoginModal.tsx
- src/components/modal/Modal.tsx
- src/components/modal/ScheduleAddModal.tsx
- src/components/modal/ScheduleEditModal.tsx
🚩 관련 이슈
ex) [FEAT] #41 - 일정등록 모달창
📋 PR Checklist
[ ] 일정 등록 모달창 퍼블리싱
📌 유의사항
모달창 크기를 늘려야하는데 크기가 고정되어 있어서 크기를 입력받을 수 있게 바꾸면 좋을 것 같긴 합니다 ! 검색해봤는데 잘안나와서,,
✅ 테스트 결과
> [FEAT] 일정등록 모달창

- src/components/button/GoogleLoginButton.tsx
- src/components/button/KakaoLoginButton.tsx
- src/components/layout/header.tsx
- src/components/modal/LoginModal.tsx
- src/components/modal/Modal.tsx
- src/components/modal/ScheduleDeleteModal.tsx
🚩 관련 이슈
ex) [FEAT] #43 - 일정 삭제 모달창 구현
📋 PR Checklist
[ ] 일정 삭제 모달창 구현
[ ] Modal창 스타일 수정으로 인한 로그인 모달창 수정
📌 유의사항
✅ 테스트 결과
> [FEAT] 일정 삭제 모달창 구현

- src/app/mybag/page.tsx
- src/components/mybag/ListComp.tsx
- src/components/mybag/MyBag.tsx
🚩 관련 이슈
ex) [FEAT] 여행 가방 페이지 구현 
📋 PR Checklist
📌 유의사항
- 삭제하기 기능의 경우 추후에 모달로 대체하기 때문에 임시로 alert로 해놨습니다.
✅ 테스트 결과
> [FEAT] 여행 가방 페이지 구현 

- public/images/bag.svg
- public/images/selectedBag.svg
- src/app/mybag/new/page.tsx
- src/components/detailschedule/CommonHeader.tsx
- src/components/detailschedule/OtherSchedule.tsx
- src/components/modal/NewBagModal.tsx
- src/components/mybag/BagList.tsx
- src/components/mybag/EmptyBag.tsx
- src/components/mybag/TopTab.tsx
🚩 관련 이슈
ex) [FEAT] #49 - 새로운 가방 만들기 페이지
📋 PR Checklist
[ ] 상단 탭 만들기
[ ] 가방 추가 모달창
[ ] 입력한 가방이름으로 가방 추가
📌 유의사항
폴더 보기 탭은 다른 PR로 만드려고합니다~!
✅ 테스트 결과
> [FEAT] 새로운 가방 만들기 페이지

- next.config.js
- src/app/info/page.tsx
- src/components/infocity/ExchangeRate.tsx
- src/components/infocity/InfoCity.tsx
- src/components/infocity/InfoWeather.tsx
🚩 관련 이슈
ex) [FEAT] #53 - 환율 api 수정 및 날씨 api 연동
📋 PR Checklist
📌 유의사항
✅ 테스트 결과
> [FEAT] 환율 api 수정 및 날씨 api 연동

- src/components/hotplace/HotPlace.tsx
🚩 관련 이슈
[FIX] #66 - 구글맵 불러올 때 오류 발생
📋 PR Checklist
📌 유의사항
✅ 테스트 결과
> [FIX] 구글맵 불러올 때 오류 발생

- package-lock.json
- package.json
- public/data/dummy.json
- src/app/info/[city]/page.tsx
- src/app/info/page.tsx
- src/components/hotplace/HotPlace.tsx
- src/components/infomenu/InfoMenus.tsx
- src/components/layout/header.tsx
- src/components/modal/SearchCityModal.tsx
🚩 관련 이슈
[FIX] #69 - 여행정보 메인페이지에서 검색했을 때 검색한 여행지로 페이지 이동
📋 PR Checklist
📌 유의사항
✅ 테스트 결과
> [FIX] 여행정보 메인페이지에서 검색했을 때 검색한 여행지로 페이지 이동

- .eslintrc.json
- src/app/schedule/page.tsx
- src/app/schedulemain/page.tsx
- src/components/hotplace/HotPlace.tsx
- src/components/infocity/ExchangeRate.tsx
- src/components/schedulemain/SelectedPlaces.tsx
- src/components/schedulemain/detailBox.tsx
- src/components/schedulemain/scheduleMain.tsx
- tsconfig.json
🚩 관련 이슈
ex) [CHORE] #79 - vercel 빌드 에러
📋 PR Checklist
[ ] build 에러 일부 수정
📌 유의사항
모듈을 불러올 수 없다는 에러 발생. 
파일명이랑 컴포넌트의 export 하는 게 달라서 그런거 같은데 파일이 너무 많아서 다 수정하기 어려움
✅ 테스트 결과
> [CHORE] vercel 빌드 에러

- src/components/mybag/BagDetail/CarrierSection.tsx
🚩 관련 이슈
ex) [FEAT] #75 - 가방 세부 페이지 준비물 추가하기
📋 PR Checklist
[ ] 가방 세부 페이지 준비물 추가하기
[ ] 목록에서 제거 이벤트
📌 유의사항
✅ 테스트 결과
> [FEAT] 가방 세부 페이지 준비물 추가하기

- src/app/mybag/detail/page.tsx
- src/components/mybag/BagDetail/CarrierSection.tsx
- src/components/mybag/BagDetail/MaterialSection.tsx
🚩 관련 이슈
ex) #76, #83 
📋 PR Checklist
[ ] 여행지별 추천준비물 클릭 시 가방에 추가
[ ] 체크박스 이슈 해결
📌 유의사항
✅ 테스트 결과
> [FEAT] 가방 세부페이지 이벤트 연결

- src/app/info/page.tsx
- src/components/infomenu/InfoMenus.tsx
- src/components/modal/FixedSearchCityModal.tsx
- src/components/modal/SearchCityModal.tsx
🚩 관련 이슈
[CHORE] #87 - 검색 컴포넌트 분리
📋 PR Checklist
📌 유의사항
✅ 테스트 결과
> [CHORE] 검색 컴포넌트 분리

- src/apis/material.ts
- src/apis/setting.ts
- src/apis/types.ts
- src/app/mybag/detail/page.tsx
- src/components/mybag/BagDetail/MaterialSection.tsx
🚩 관련 이슈
ex) #90 
📋 PR Checklist
[ ] axios instance  생성
[ ] API 타입 지정
📌 유의사항
✅ 테스트 결과
> [CHORE] API 인터페이스 생성

- src/apis/types.ts
- src/apis/user.ts
- src/app/auth/google/page.tsx
- src/app/auth/kakao/page.tsx
- src/components/button/KakaoLoginButton.tsx
- src/utils/oauth.ts
🚩 관련 이슈
ex) #94 
📋 PR Checklist
[ ] 카카오 로그인
[ ] 구글 로그인
[ ] 액세스토큰 갱신
[ ] 로그아웃
[ ] API 타입 지정
📌 유의사항
✅ 테스트 결과
> [FEAT] auth API 인터페이스 구현

- src/app/signup/page.tsx
- src/components/button/GoogleLoginButton.tsx
- src/components/button/KakaoLoginButton.tsx
- src/components/layout/header.tsx
- src/components/modal/LoginModal.tsx
- src/components/modal/LoginSignUpModal.tsx
- src/components/modal/SignUpDoneModal.tsx
- tailwind.config.js
🚩 관련 이슈
[FEAT] #108 - 회원가입 퍼블리싱
📋 PR Checklist
<h2>로그인 클릭 시</h2>
<h2>회원가입 클릭 시</h2>
📌 유의사항
- 회원가입 페이지는 /signup으로 들어가면 됩니다.
✅ 테스트 결과
> [FEAT] 회원가입 퍼블리싱

- src/apis/setting.ts
- src/apis/user/friend.ts
- src/apis/user/types.ts
- src/app/auth/kakao/page.tsx
- src/app/mypage/page.tsx
- src/components/layout/header.tsx
- src/components/mypage/myInfo.tsx
- src/components/mypagefriend/follower.tsx
- src/components/mypagefriend/following.tsx
- src/components/mypagefriend/friendOneBtn.tsx
- src/components/mypagefriend/friendReq.tsx
- src/components/mypagefriend/friendTwoBtn.tsx
- src/components/mypagefriend/myFriends.tsx
- src/components/mypagefriend/sendFollow.tsx
🚩 관련 이슈
ex) resolve #107 
📋 PR Checklist
[ ] 친구 요청, 친구 끊기, 친구 차단 API 연동
[ ] 요청 취소, 요청 수락, 요청 거절 API 연동
[ ] 로그인 유지
📌 유의사항
✅ 테스트 결과
> [FEAT] 친구 API 연동

- src/apis/user/login.ts
- src/components/layout/header.tsx
- src/components/mypage/confirmBtns.tsx
🚩 관련 이슈
ex) resolve #111 
📋 PR Checklist
[ ] 로그아웃
[ ] 회원탈퇴
📌 유의사항
✅ 테스트 결과
> [FEAT] 로그아웃, 회원탈퇴 API 연동

- src/apis/user/login.ts
- src/app/mypage/page.tsx
- src/components/layout/confirmBtn.tsx
- src/components/layout/header.tsx
- src/components/mypage/confirmBtns.tsx
- src/components/mypage/infoInput.tsx
- src/components/mypage/myInfo.tsx
- src/components/mypage/profilePic.tsx
🚩 관련 이슈
ex) #113 
📋 PR Checklist
[ ] 내 정보 수정 API 연동
[ ] 이미지 업로드
📌 유의사항
s3 업로드 구현 필요
✅ 테스트 결과
> [FEAT] 회원정보 수정 API 연동

- src/apis/types.ts
- src/apis/user/friend.ts
- src/apis/user/login.ts
- src/app/auth/google/page.tsx
- src/app/auth/kakao/page.tsx
- src/app/mypage/page.tsx
- src/app/signup/page.tsx
- src/components/mypage/infoInput.tsx
- src/states/user.ts
🚩 관련 이슈
ex) resolve #124 
📋 PR Checklist
[ ] 구글 로그인
[ ] 회원가입 로직 추가
📌 유의사항
✅ 테스트 결과
> [FEAT] 구글 로그인 및 회원가입 로직 연결

- src/apis/travellists/check.ts
- src/apis/travellists/update.ts
- src/app/info/[city]/page.tsx
- src/app/info/page.tsx
- src/app/newschedule/page.tsx
- src/app/updateschedule/page.tsx
- src/components/conversation/Conversation.tsx
- src/components/detailschedule/BlockSchedule.tsx
- src/components/detailschedule/LabelSchedules.tsx
- src/components/detailschedule/OtherSchedule.tsx
- src/components/hotplace/Places.tsx
- src/components/infomenu/InfoMenus.tsx
- src/components/main/CardCarousel.tsx
- src/components/modal/ScheduleAddInnerModal.tsx
- src/components/mypage/MyBagList.tsx
- src/components/mypage/MyTravelList.tsx
- src/components/scheduleblock/ScheduleBlock.tsx
- src/components/schedulemain/detailBox.tsx
- src/components/schedulemain/myTravel.tsx
- src/components/schedulemain/scheduleMain.tsx
- src/components/summary/MyTravel.tsx
🚩 관련 이슈
[FEAT] #129 - 여행 일정 등록 API 수정
📋 PR Checklist
📌 유의사항
✅ 테스트 결과
> [FEAT] 여행 일정 등록 API 수정

- src/apis/bag/index.ts
- src/apis/bag/types.ts
- src/apis/types.ts
- src/apis/user/friend.ts
- src/apis/user/login.ts
- src/app/mybag/detail/[bid]/page.tsx
- src/app/mybag/detail/page.tsx
- src/app/mybag/new/page.tsx
- src/app/mypage/page.tsx
- src/components/detailschedule/OtherSchedule.tsx
- src/components/modal/SelectScheduleModal.tsx
- src/components/mybag/BagDetail/CarrierSection.tsx
- src/components/mybag/BagDetail/MemoSection.tsx
- src/components/mybag/BagList.tsx
- src/components/mypage/confirmBtns.tsx
- src/states/schedule.ts
- src/types/bag.ts
- src/types/user.ts
🚩 관련 이슈
ex) resolve #128 
📋 PR Checklist
[ ] 준비물 추가, 수정, 삭제
[ ] 특정 일정에 가방 추가
[ ] 가방마다 다른 준비물 조회
📌 유의사항
✅ 테스트 결과
> [FEAT] 여행가방 API 연동

- src/apis/bag/index.ts
- src/apis/bag/types.ts
- src/apis/user/friend.ts
- src/apis/user/types.ts
- src/app/mybag/detail/[bid]/page.tsx
- src/app/mybag/new/page.tsx
- src/app/newschedule/page.tsx
- src/app/updateschedule/page.tsx
- src/components/conversation/Conversation.tsx
- src/components/detailschedule/DetailSchedule.tsx
- src/components/detailschedule/FriendList.tsx
- src/components/layout/header.tsx
- src/components/layout/roundBtn.tsx
- src/components/modal/FriendListModal.tsx
- src/components/modal/ScheduleListModal.tsx
- src/components/mybag/BagDetail/MaterialSection.tsx
- src/components/mybag/BagDetail/MemoSection.tsx
- src/components/mypagefriend/friendOneBtn.tsx
- src/components/mypagefriend/myFriends.tsx
- src/types/bag.ts
- src/types/user.ts
- src/utils/dateUtil.ts
🚩 관련 이슈
- resolve #135 , 
- resolve #137 
📋 PR Checklist
[ ] 가방 내부 메모 조회
[ ] 여행지별 준비물 조회
[ ] 친구 일정에 초대
[ ] 일정 공유 중인 친구 조회
📌 유의사항
로그인 유지 코드 주석해제
✅ 테스트 결과
> [FEAT] 친구초대 및 일정에 초대된 친구 조회 연동
